version: 0.0
os: linux
files:
  - source: /
    destination: /opt
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/stop_server
      timeout: 300
#      runas: root

  AfterInstall:
    - location: scripts/install_dependencies
#      runas: root
    - location: scripts/start_server
      timeout: 300
#      runas: root

  ApplicationStart:
    - location: scripts/register_with_elb.sh
