#!/bin/bash

cd /var/www/magic8ball/magic8ball
/usr/bin/python ./get-pip.py
pip install virtualenv
virtualenv venv
source ./venv/bin/activate
pip install flask
pip install flask-bootstrap
pip install boto
